# Generated by Django 3.1.7 on 2022-04-10 13:46

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itempedido',
            name='total',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='BRL', max_digits=14, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=djmoney.models.fields.MoneyField(blank=True, decimal_places=2, default_currency='BRL', max_digits=14, null=True),
        ),
    ]
