#! /usr/bin/python
# -*- coding: UTF-8 -*-
"""
Global variables for base module
"""
from django.utils.translation import ugettext_lazy as _
from django.conf import LazySettings

settings = LazySettings()


def get_from_settings_or_default(var_name, default):
    try:
        return settings.__getattr__(var_name)
    except AttributeError:
        return default


# Items by page on paginator views
ITEMS_BY_PAGE = 10

CREATE_SUFFIX = "_create"
LIST_SUFFIX = "_list"
DETAIL_SUFFIX = "_detail"
UPDATE_SUFFIX = "_update"
DELETE_SUFFIX = "_delete"

API_SUFFIX = "_api"
style = "base_django/flexbox"


# Messages
OBJECT_CREATED_SUCCESSFULLY = _("Object created successfully")
OBJECT_UPDATED_SUCCESSFULLY = _("Object updated successfully")
OBJECT_DELETED_SUCCESSFULLY = _("Object deleted successfully")

BASE_MODELS_TRANSLATION_NAME = _("Name")
BASE_MODELS_TRANSLATION_DESCRIPTION = _("Description")
BASE_MODELS_TRANSLATION_SLUG = _("Slug")
BASE_MODELS_TRANSLATION_CREATED = _("Created")
BASE_MODELS_TRANSLATION_MODIFIED = _("Modified")
BASE_MODELS_TRANSLATION_ACTIVE = _("Active")

CONFIGURING_APPLICATION = _("Configuring application {}")
CREATING_PERMISSION_WITH_NAME = _("Creating Permission with name {}")
CREATING_GROUP_WITH_NAME = _("Creating Group with name {}")


TIPOITEM_PREFIX = "TIPOITEM"

TIPOITEM_VERBOSE_NAME = _("TipoItem")
TIPOITEM_VERBOSE_NAME_PLURAL = _("TipoItem")

TIPOITEM_LIST_URL_NAME = TIPOITEM_PREFIX + LIST_SUFFIX
TIPOITEM_CREATE_URL_NAME = TIPOITEM_PREFIX + CREATE_SUFFIX
TIPOITEM_DETAIL_URL_NAME = TIPOITEM_PREFIX + DETAIL_SUFFIX
TIPOITEM_UPDATE_URL_NAME = TIPOITEM_PREFIX + UPDATE_SUFFIX
TIPOITEM_DELETE_URL_NAME = TIPOITEM_PREFIX + DELETE_SUFFIX
TIPOITEM_LIST_JSON_URL_NAME = TIPOITEM_PREFIX + '_list_json'


ITEM_PREFIX = "ITEM"

ITEM_VERBOSE_NAME = _("Item")
ITEM_VERBOSE_NAME_PLURAL = _("Item")

ITEM_LIST_URL_NAME = ITEM_PREFIX + LIST_SUFFIX
ITEM_CREATE_URL_NAME = ITEM_PREFIX + CREATE_SUFFIX
ITEM_DETAIL_URL_NAME = ITEM_PREFIX + DETAIL_SUFFIX
ITEM_UPDATE_URL_NAME = ITEM_PREFIX + UPDATE_SUFFIX
ITEM_DELETE_URL_NAME = ITEM_PREFIX + DELETE_SUFFIX
ITEM_LIST_JSON_URL_NAME = ITEM_PREFIX + '_list_json'


PEDIDO_PREFIX = "PEDIDO"

PEDIDO_VERBOSE_NAME = _("Pedido")
PEDIDO_VERBOSE_NAME_PLURAL = _("Pedido")

PEDIDO_LIST_URL_NAME = PEDIDO_PREFIX + LIST_SUFFIX
PEDIDO_CREATE_URL_NAME = PEDIDO_PREFIX + CREATE_SUFFIX
PEDIDO_DETAIL_URL_NAME = PEDIDO_PREFIX + DETAIL_SUFFIX
PEDIDO_UPDATE_URL_NAME = PEDIDO_PREFIX + UPDATE_SUFFIX
PEDIDO_DELETE_URL_NAME = PEDIDO_PREFIX + DELETE_SUFFIX
PEDIDO_LIST_JSON_URL_NAME = PEDIDO_PREFIX + '_list_json'


ITEMPEDIDO_PREFIX = "ITEMPEDIDO"

ITEMPEDIDO_VERBOSE_NAME = _("ItemPedido")
ITEMPEDIDO_VERBOSE_NAME_PLURAL = _("ItemPedido")

ITEMPEDIDO_LIST_URL_NAME = ITEMPEDIDO_PREFIX + LIST_SUFFIX
ITEMPEDIDO_CREATE_URL_NAME = ITEMPEDIDO_PREFIX + CREATE_SUFFIX
ITEMPEDIDO_DETAIL_URL_NAME = ITEMPEDIDO_PREFIX + DETAIL_SUFFIX
ITEMPEDIDO_UPDATE_URL_NAME = ITEMPEDIDO_PREFIX + UPDATE_SUFFIX
ITEMPEDIDO_DELETE_URL_NAME = ITEMPEDIDO_PREFIX + DELETE_SUFFIX
ITEMPEDIDO_LIST_JSON_URL_NAME = ITEMPEDIDO_PREFIX + '_list_json'

